source 'https://api.berkshelf.com'

cookbook 'toruzou-cookbook', path: 'site-cookbooks/toruzou-cookbook'
cookbook 'python'
cookbook 'postgresql'
cookbook 'application_ruby'
cookbook 'rbenv'
cookbook 'nodejs'
cookbook 'yum-epel'
cookbook 'vim'
